home_site_index:
    path:     /
    defaults: { _controller: "FrontSiteBundle:TzHome:index" }
    methods:  GET

home_site_gallery:
    path:     /gallery
    defaults: { _controller: "FrontSiteBundle:TzHome:gallery" }
    methods:  GET

