membres_liste:
  path:     /
  defaults: { _controller: "FrontSiteBundle:TzMembres:index" }

#membres_new:
#  path:     /new
#  defaults: { _controller: "FrontSiteBundle:TzMembres:new" }
#  methods: [GET,POST]

membres_show:
  path:     /{id}/show
  defaults: { _controller: "FrontSiteBundle:TzMembres:show" }
  methods: GET