tz_home_site:
    resource: "@FrontSiteBundle/Resources/config/routing/home.yml"
    prefix:   /

tz_membres_liste:
  resource: "@FrontSiteBundle/Resources/config/routing/membres.yml"
  prefix:     /membres

tz_article:
  resource: "@FrontSiteBundle/Resources/config/routing/article.yml"
  prefix:     /article

tz_hiu:
  resource: "@FrontSiteBundle/Resources/config/routing/hiu.yml"
  prefix:     /hiu

tz_programme:
  resource: "@FrontSiteBundle/Resources/config/routing/programme.yml"
  prefix:     /